[colors.bright]
black = "#1e3242"
blue = "#d4c6ff"
cyan = "#bde4ff"
green = "#92fecf"
magenta = "#ffb2f8"
red = "#ffa8ac"
white = "#ffffff"
yellow = "#e5ffdb"

[colors.normal]
black = "#162532"
blue = "#bfaaff"
cyan = "#9cd6ff"
green = "#5bfeb7"
magenta = "#ff8cf4"
red = "#ff7c83"
white = "#ccd4da"
yellow = "#d8ffc9"

[colors.primary]
background = "#162532"
foreground = "#ffffff"
